# main/__init__.py
# PyRo-FOAMS package root
"""
PyRo-FOAMS - Pore/Foam Image Analysis Toolkit

Subpackages:
    core - Pure algorithms (thresholding, watershed, measurements)
    gui  - Tkinter-based user interfaces

Quick start:
    python -m main          # Launch GUI

    # Or use core algorithms directly:
    from main.core import thresholdImageAdvanced, measure_labels
"""

# Re-export commonly used items from core for convenience
from .core import (
    # Calibrated sampling
    CANONICAL_LENGTH_UNIT,
    COMPATIBILITY_STATUS,
    # Processing
    DEFAULTS,
    DETECTION_ELIGIBILITY_POLICY,
    FOAMS105_COEFFICIENT_LOG10_STEP,
    FOAMS105_HEIGHT_POLICY,
    FOAMS105_MAX_CLASSES,
    FOAMS105_METHOD,
    FOAMS105_SCOPE,
    FOAMS105_SMALLEST_CLASS_POLICY,
    FOAMS105_SOURCE_COMMIT,
    FOAMS105_SOURCE_FILE,
    FOAMS105_SOURCE_REPOSITORY,
    NESTING_METHOD,
    RECONSTRUCTION_METHOD,
    SECTION_MODEL_ASSUMPTION,
    SPHERE_MODEL_ASSUMPTION,
    UPPER_TAIL_ASSUMPTION,
    AnalysisDomainError,
    DiameterBin,
    DiameterBinSpec,
    DistributionDiagnostics,
    DistributionResult,
    DistributionValidationError,
    Foams105ConversionResult,
    Foams105NumericalError,
    Foams105ValidationError,
    Group2DDistribution,
    ImageSamplingRecord,
    MeasurementMappingError,
    Nested2DDistribution,
    NestingPlan,
    NestingSegment,
    NestingTransition,
    NestingValidationError,
    OverlapBinComparison,
    # Stereology
    PoreProps,
    ReconstructionNumericalError,
    ReconstructionValidationError,
    SampledPore,
    SamplingDataset,
    SamplingGroupSummary,
    SamplingValidationError,
    SphericalInverseResult,
    SphericalReconstructionResult,
    SphericalSectionOperator,
    TransitionOverlapDiagnostics,
    UnsupportedUnitError,
    # Preprocessing
    applyCropBatch,
    build_sampling_dataset,
    build_spherical_section_operator,
    calculate_2d_number_densities,
    clampRectToImage,
    clearBorderTouching,
    colorize_labels,
    convert_foams105_nv,
    create_diameter_bin_spec,
    create_image_sampling_record,
    cropWithMargins,
    cropWithRect,
    fillHoles,
    geometric_diameter_bin_spec,
    labelsToColor,
    length_to_mm,
    loadImage,
    marginsToRect,
    mask_from_labels,
    # Batch
    measure_batch,
    measure_dataset,
    measure_labels,
    nest_2d_distribution,
    normalize_length_unit,
    postSeparateCleanup,
    process_batch_parallel,
    process_batch_sequential,
    project_spherical_number_densities,
    reconstruct_spherical_3d,
    rectToMargins,
    removeSmallAreas,
    runSeparationPipeline,
    save_props_csv,
    solve_spherical_number_densities,
    summarize_sampling_groups,
    threshold_batch,
    thresholdImageAdvanced,
    watershedSeparate,
)

__all__ = [
    # Processing
    "DEFAULTS",
    "thresholdImageAdvanced",
    "fillHoles",
    "removeSmallAreas",
    "clearBorderTouching",
    "watershedSeparate",
    "postSeparateCleanup",
    "labelsToColor",
    "runSeparationPipeline",
    # Stereology
    "PoreProps",
    "colorize_labels",
    "measure_labels",
    "measure_dataset",
    "save_props_csv",
    "mask_from_labels",
    # Calibrated sampling
    "CANONICAL_LENGTH_UNIT",
    "SamplingValidationError",
    "UnsupportedUnitError",
    "AnalysisDomainError",
    "MeasurementMappingError",
    "ImageSamplingRecord",
    "SampledPore",
    "SamplingDataset",
    "SamplingGroupSummary",
    "normalize_length_unit",
    "length_to_mm",
    "create_image_sampling_record",
    "build_sampling_dataset",
    "summarize_sampling_groups",
    # 2D distributions
    "DETECTION_ELIGIBILITY_POLICY",
    "DistributionValidationError",
    "DiameterBin",
    "DiameterBinSpec",
    "DistributionDiagnostics",
    "Group2DDistribution",
    "DistributionResult",
    "create_diameter_bin_spec",
    "geometric_diameter_bin_spec",
    "calculate_2d_number_densities",
    # FOAMS 1.0.5 post-nesting conversion replay
    "FOAMS105_METHOD",
    "FOAMS105_SOURCE_REPOSITORY",
    "FOAMS105_SOURCE_COMMIT",
    "FOAMS105_SOURCE_FILE",
    "FOAMS105_SMALLEST_CLASS_POLICY",
    "FOAMS105_HEIGHT_POLICY",
    "FOAMS105_SCOPE",
    "FOAMS105_COEFFICIENT_LOG10_STEP",
    "FOAMS105_MAX_CLASSES",
    "Foams105ValidationError",
    "Foams105NumericalError",
    "Foams105ConversionResult",
    "convert_foams105_nv",
    # Manual magnification nesting
    "NESTING_METHOD",
    "NestingValidationError",
    "NestingSegment",
    "NestingPlan",
    "NestingTransition",
    "OverlapBinComparison",
    "TransitionOverlapDiagnostics",
    "Nested2DDistribution",
    "nest_2d_distribution",
    # Spherical 3D reconstruction
    "RECONSTRUCTION_METHOD",
    "COMPATIBILITY_STATUS",
    "UPPER_TAIL_ASSUMPTION",
    "SPHERE_MODEL_ASSUMPTION",
    "SECTION_MODEL_ASSUMPTION",
    "ReconstructionValidationError",
    "ReconstructionNumericalError",
    "SphericalSectionOperator",
    "SphericalInverseResult",
    "SphericalReconstructionResult",
    "build_spherical_section_operator",
    "project_spherical_number_densities",
    "solve_spherical_number_densities",
    "reconstruct_spherical_3d",
    # Preprocessing
    "loadImage",
    "clampRectToImage",
    "rectToMargins",
    "marginsToRect",
    "cropWithRect",
    "cropWithMargins",
    "applyCropBatch",
    # Batch
    "process_batch_parallel",
    "process_batch_sequential",
    "threshold_batch",
    "measure_batch",
]
