# main/core/__init__.py
# Core algorithms package - pure callables with no GUI dependencies
# Safe for headless testing, multiprocessing, and parallelism

from .batch import (
    measure_batch,
    process_batch_parallel,
    process_batch_sequential,
    threshold_batch,
)
from .distributions import (
    DETECTION_ELIGIBILITY_POLICY,
    DiameterBin,
    DiameterBinSpec,
    DistributionDiagnostics,
    DistributionResult,
    DistributionValidationError,
    Group2DDistribution,
    calculate_2d_number_densities,
    create_diameter_bin_spec,
    geometric_diameter_bin_spec,
)
from .legacy_foams import (
    FOAMS105_COEFFICIENT_LOG10_STEP,
    FOAMS105_HEIGHT_POLICY,
    FOAMS105_MAX_CLASSES,
    FOAMS105_METHOD,
    FOAMS105_SCOPE,
    FOAMS105_SMALLEST_CLASS_POLICY,
    FOAMS105_SOURCE_COMMIT,
    FOAMS105_SOURCE_FILE,
    FOAMS105_SOURCE_REPOSITORY,
    Foams105ConversionResult,
    Foams105NumericalError,
    Foams105ValidationError,
    convert_foams105_nv,
)
from .nesting import (
    NESTING_METHOD,
    Nested2DDistribution,
    NestingPlan,
    NestingSegment,
    NestingTransition,
    NestingValidationError,
    OverlapBinComparison,
    TransitionOverlapDiagnostics,
    nest_2d_distribution,
)
from .preprocessing import (
    applyCropBatch,
    clampRectToImage,
    cropWithMargins,
    cropWithRect,
    loadImage,
    marginsToRect,
    rectToMargins,
)
from .processing import (
    DEFAULTS,
    clearBorderTouching,
    fillHoles,
    labelsToColor,
    postSeparateCleanup,
    removeSmallAreas,
    runSeparationPipeline,
    thresholdImageAdvanced,
    watershedSeparate,
)
from .reconstruction import (
    COMPATIBILITY_STATUS,
    RECONSTRUCTION_METHOD,
    SECTION_MODEL_ASSUMPTION,
    SPHERE_MODEL_ASSUMPTION,
    UPPER_TAIL_ASSUMPTION,
    ReconstructionNumericalError,
    ReconstructionValidationError,
    SphericalInverseResult,
    SphericalReconstructionResult,
    SphericalSectionOperator,
    build_spherical_section_operator,
    project_spherical_number_densities,
    reconstruct_spherical_3d,
    solve_spherical_number_densities,
)
from .sampling import (
    CANONICAL_LENGTH_UNIT,
    AnalysisDomainError,
    ImageSamplingRecord,
    MeasurementMappingError,
    SampledPore,
    SamplingDataset,
    SamplingGroupSummary,
    SamplingValidationError,
    UnsupportedUnitError,
    build_sampling_dataset,
    create_image_sampling_record,
    length_to_mm,
    normalize_length_unit,
    summarize_sampling_groups,
)
from .stereology import (
    PoreProps,
    colorize_labels,
    mask_from_labels,
    measure_dataset,
    measure_labels,
    save_props_csv,
)

__all__ = [
    # processing
    "DEFAULTS",
    "thresholdImageAdvanced",
    "fillHoles",
    "removeSmallAreas",
    "clearBorderTouching",
    "watershedSeparate",
    "postSeparateCleanup",
    "labelsToColor",
    "runSeparationPipeline",
    # stereology
    "PoreProps",
    "colorize_labels",
    "measure_labels",
    "measure_dataset",
    "save_props_csv",
    "mask_from_labels",
    # calibrated sampling
    "CANONICAL_LENGTH_UNIT",
    "SamplingValidationError",
    "UnsupportedUnitError",
    "AnalysisDomainError",
    "MeasurementMappingError",
    "ImageSamplingRecord",
    "SampledPore",
    "SamplingDataset",
    "SamplingGroupSummary",
    "normalize_length_unit",
    "length_to_mm",
    "create_image_sampling_record",
    "build_sampling_dataset",
    "summarize_sampling_groups",
    # 2D distributions
    "DETECTION_ELIGIBILITY_POLICY",
    "DistributionValidationError",
    "DiameterBin",
    "DiameterBinSpec",
    "DistributionDiagnostics",
    "Group2DDistribution",
    "DistributionResult",
    "create_diameter_bin_spec",
    "geometric_diameter_bin_spec",
    "calculate_2d_number_densities",
    # FOAMS 1.0.5 post-nesting conversion replay
    "FOAMS105_METHOD",
    "FOAMS105_SOURCE_REPOSITORY",
    "FOAMS105_SOURCE_COMMIT",
    "FOAMS105_SOURCE_FILE",
    "FOAMS105_SMALLEST_CLASS_POLICY",
    "FOAMS105_HEIGHT_POLICY",
    "FOAMS105_SCOPE",
    "FOAMS105_COEFFICIENT_LOG10_STEP",
    "FOAMS105_MAX_CLASSES",
    "Foams105ValidationError",
    "Foams105NumericalError",
    "Foams105ConversionResult",
    "convert_foams105_nv",
    # manual magnification nesting
    "NESTING_METHOD",
    "NestingValidationError",
    "NestingSegment",
    "NestingPlan",
    "NestingTransition",
    "OverlapBinComparison",
    "TransitionOverlapDiagnostics",
    "Nested2DDistribution",
    "nest_2d_distribution",
    # spherical 3D reconstruction
    "RECONSTRUCTION_METHOD",
    "COMPATIBILITY_STATUS",
    "UPPER_TAIL_ASSUMPTION",
    "SPHERE_MODEL_ASSUMPTION",
    "SECTION_MODEL_ASSUMPTION",
    "ReconstructionValidationError",
    "ReconstructionNumericalError",
    "SphericalSectionOperator",
    "SphericalInverseResult",
    "SphericalReconstructionResult",
    "build_spherical_section_operator",
    "project_spherical_number_densities",
    "solve_spherical_number_densities",
    "reconstruct_spherical_3d",
    # preprocessing
    "loadImage",
    "clampRectToImage",
    "rectToMargins",
    "marginsToRect",
    "cropWithRect",
    "cropWithMargins",
    "applyCropBatch",
    # batch parallel
    "process_batch_parallel",
    "process_batch_sequential",
    "threshold_batch",
    "measure_batch",
]
